// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:omode/constants.dart' as Constants;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Constants.FIREBASE_API_KEY_WEB,
    appId: '1:308381275742:web:05c48c2350a68b859546cf',
    messagingSenderId: '308381275742',
    projectId: 'fcmtest-2fcba',
    authDomain: 'fcmtest-2fcba.firebaseapp.com',
    databaseURL: 'https://fcmtest-2fcba.firebaseio.com',
    storageBucket: 'fcmtest-2fcba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Constants.FIREBASE_API_KEY_ANDROID,
    appId: '1:308381275742:android:ab4c09740dde23979546cf',
    messagingSenderId: '308381275742',
    projectId: 'fcmtest-2fcba',
    databaseURL: 'https://fcmtest-2fcba.firebaseio.com',
    storageBucket: 'fcmtest-2fcba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Constants.FIREBASE_API_KEY_IOS,
    appId: '1:308381275742:ios:0a6ea7808399e5a39546cf',
    messagingSenderId: '308381275742',
    projectId: 'fcmtest-2fcba',
    databaseURL: 'https://fcmtest-2fcba.firebaseio.com',
    storageBucket: 'fcmtest-2fcba.appspot.com',
    iosClientId: '308381275742-25957mosvrhhas4c7uc361jein0g0309.apps.googleusercontent.com',
    iosBundleId: 'com.laxusgooee.omode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Constants.FIREBASE_API_KEY_MACOS,
    appId: '1:308381275742:ios:0a6ea7808399e5a39546cf',
    messagingSenderId: '308381275742',
    projectId: 'fcmtest-2fcba',
    databaseURL: 'https://fcmtest-2fcba.firebaseio.com',
    storageBucket: 'fcmtest-2fcba.appspot.com',
    iosClientId: '308381275742-25957mosvrhhas4c7uc361jein0g0309.apps.googleusercontent.com',
    iosBundleId: 'com.laxusgooee.omode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Constants.FIREBASE_API_KEY_WINDOWS,
    appId: '1:308381275742:web:c722eb83585c79d09546cf',
    messagingSenderId: '308381275742',
    projectId: 'fcmtest-2fcba',
    authDomain: 'fcmtest-2fcba.firebaseapp.com',
    databaseURL: 'https://fcmtest-2fcba.firebaseio.com',
    storageBucket: 'fcmtest-2fcba.appspot.com',
  );
}
